### ISSUE TITLE
Duplicate MQTT Loop Threads

### ISSUE THREAD

**Issue by Shiny380** [NubeDev/bacnet-flask#35]
https://github.com/NubeDev/bacnet-flask/blob/master/src/bacnet_server/mqtt_connection.py#L29
`MqttConnection.__client.loop_start()` kicks off its own thread
and
`MqttConnection.__client.loop_forever()` is running it's own blocking loop in called thread
Only need one or the other

**Comment by RaiBnod** [comment]
Cool, I didn't know we have `client.loop_start` function to start on it's own thread.
